In [74]:
import torch
from torch.utils.data import Dataset, DataLoader
from transformers import AutoTokenizer, AutoModelForSequenceClassification, TrainingArguments, Trainer, EarlyStoppingCallback
import numpy as np
from sklearn.metrics import accuracy_score, f1_score
import pandas as pd
pd.set_option('display.max_rows', 20)

In [75]:
# 1. Создаём свой класс Dataset для PyTorch
class IntentDataset(Dataset):
    def __init__(self, texts, labels, tokenizer, max_length=128):
        self.texts = texts
        self.labels = labels
        self.tokenizer = tokenizer
        self.max_length = max_length
    
    def __len__(self):
        return len(self.texts)
    
    def __getitem__(self, idx):
        text = str(self.texts[idx])
        label = self.labels[idx]
        
        # Токенизируем текст
        encoding = self.tokenizer(
            text,
            truncation=True,
            padding='max_length',
            max_length=self.max_length,
            return_tensors='pt'
        )
        
        return {
            'input_ids': encoding['input_ids'].flatten(),
            'attention_mask': encoding['attention_mask'].flatten(),
            'labels': torch.tensor(label, dtype=torch.long)
        }

In [76]:
import pandas as pd

df = pd.read_csv('../dataset/extended_by_deepseek_3.csv', sep=',')
df = df[df['тема'].notna()]
df = df[df['текст'].notna()]
df = df[['тема', 'текст']]

# темы, по которым пока не был получен ответ от deepseek:
df = df[df['тема'] != "вышка тура"]
df = df[df['тема'] != "плиткорез электрический"]
df = df[df['тема'] != "реноватор аккумуляторный"]
df = df[df['тема'] != "присоска"]
df = df[df['тема'] != "нивелир оптический"]
df = df[df['тема'] != "детектор проводки"]
df = df[df['тема'] != "дрель магнитная"]

# df = df[df['тема'] != "не вопрос клиента"]
df

                   тема                                              текст
0      дрель-шуруповерт  добрый вечер! подскажите, у вас можно взять в ...
1               пылесос  Здравствуйте) сколько стоит аренда строительно...
2      плиткорез ручной  Доброе утро. Подскажите пожалуйста в какую цен...
3                   фен  Доброе утро Есть строительный фен на аккумулят...
4     не вопрос клиента                                        Добрый день
...                 ...                                                ...
1492     пароочиститель   'Здравствуйте, есть ли в прокате устройство д...
1493     пароочиститель   'Привет, сколько стоит арендовать пароочистит...
1494     пароочиститель   'Добрый день, нужен пароочиститель для уборки...
1495     пароочиститель   'Здравствуйте, подскажите, можно ли взять пар...
1496     пароочиститель   'Добрый вечер, есть ли у вас аппарат для чист...

[1496 rows x 2 columns]

In [77]:
def clear_text(text: str) -> str:
    # функция очистки текстов от паразитных слов, не относящихся к теме запроса
    
    trash_values = [
        'добрый вечер', 
        'добрый день', 
        'доброе утро',
        'добрый утро',
        'здравствуйте',
        'подскажите',
        'пожалуйста',
        'хотелось',
        'интересует',
        'нужен',
        'нужно',
        'хочу',
        'надо',
        'можно',
        'аренда',
        'аренду',
        'хочу',
        'хотел бы',
        'в наличии',
        'сколько стоит',
        ',',
        "'",
    ]
    text = text.lower()
    for value in trash_values:
        text = text.replace(value, '')
    return text

In [78]:
df['текст'] = df['текст'].map(clear_text)
df

                   тема                                              текст
0      дрель-шуруповерт                      !  у вас  взять в  шурповерт?
1               пылесос               )   строительного пылесоса на сутки?
2      плиткорез ручной  .   в какую цену у вас следующие инструменты: ...
3                   фен   есть строительный фен на аккумуляторной батареи?
4     не вопрос клиента
...                 ...                                                ...
1492     пароочиститель    есть ли в прокате устройство для чистки паро...
1493     пароочиститель   привет  арендовать пароочиститель для чистки ...
1494     пароочиститель     пароочиститель для уборки после ремонта есть ?
1495     пароочиститель                  ли взять пароочиститель на сутки?
1496     пароочиститель    есть ли у вас аппарат для чистки паром  почи...

[1496 rows x 2 columns]

In [79]:
df['номер темы'] = df['тема'].astype('category').cat.codes
df

,тема,текст,номер темы
0,дрель-шуруповерт,! у вас взять в шурповерт?,19
1,пылесос,) строительного пылесоса на сутки?,59
2,плиткорез ручной,. в какую цену у вас следующие инструменты: ...,51
3,фен,есть строительный фен на аккумуляторной батареи?,76
4,не вопрос клиента,,36
...,...,...,...
1492,пароочиститель,есть ли в прокате устройство для чистки паро...,42
1493,пароочиститель,привет арендовать пароочиститель для чистки ...,42
1494,пароочиститель,пароочиститель для уборки после ремонта есть ?,42
1495,пароочиститель,ли взять пароочиститель на сутки?,42
1496,пароочиститель,есть ли у вас аппарат для чистки паром почи...,42

In [80]:
df_small = df[df['тема']=='бензорез']
df_small

          тема                                              текст  номер темы
34    бензорез                           .   бензорез у вас есть?           5
254   бензорез                           у вас есть в  бетонорез?           5
678   бензорез       бензорез под 400 диск хускварна. есть такой?           5
809   бензорез  .  с большим диском по бетону на сутки по како...           5
881   бензорез    есть ли бензорез с 400 диском в  на одни сутки?           5
1076  бензорез            бензорез для резки металла на завтра  ?           5
1077  бензорез    \n есть ли у вас  бензорез для демонтажа заб...           5
1078  бензорез    \nпривет  взять бензорез на пару часов чтобы...           5
1079  бензорез           \n   ли арендовать бензорез на выходные?           5
1080  бензорез      \n  взять бензорез на сутки  резать арматуру?           5
1081  бензорез    \n ищу бензорез для резки бетона есть у вас ...           5
1082  бензорез    \nпривет  бензорез для резки кирпича какие д...           5
1083  бензорез    \n  ли арендовать бензорез сегодня после 18:00?           5
1084  бензорез            \n  бензорез для резки плитки  на день?           5
1085  бензорез    \n есть ли у вас бензорез с алмазным диском ...           5

In [81]:
summary = df['тема'].value_counts()
print(summary)

тема
не вопрос клиента                126
перфоратор                        78
пылесос                           65
дрель-шуруповерт                  55
торцовочная пила                  45
                                ...
сабельная пила аккумуляторная     11
домкрат подкатной                 11
миксер                            10
сварочный аппарат                 10
Отбойный молоток                  10
Name: count, Length: 82, dtype: int64

In [82]:
# Применяем маску: оставляем только те строки, где размер темы >= 5
mask = df.groupby('тема')['тема'].transform('size') >= 5
df = df[mask]
df['номер темы'] = df['тема'].astype('category').cat.codes
df

,тема,текст,номер темы
0,дрель-шуруповерт,! у вас взять в шурповерт?,19
1,пылесос,) строительного пылесоса на сутки?,59
2,плиткорез ручной,. в какую цену у вас следующие инструменты: ...,51
3,фен,есть строительный фен на аккумуляторной батареи?,76
4,не вопрос клиента,,36
...,...,...,...
1492,пароочиститель,есть ли в прокате устройство для чистки паро...,42
1493,пароочиститель,привет арендовать пароочиститель для чистки ...,42
1494,пароочиститель,пароочиститель для уборки после ремонта есть ?,42
1495,пароочиститель,ли взять пароочиститель на сутки?,42
1496,пароочиститель,есть ли у вас аппарат для чистки паром почи...,42

In [83]:
summary = df['тема'].value_counts()
print(summary)

тема
не вопрос клиента                126
перфоратор                        78
пылесос                           65
дрель-шуруповерт                  55
торцовочная пила                  45
                                ...
сабельная пила аккумуляторная     11
домкрат подкатной                 11
миксер                            10
сварочный аппарат                 10
Отбойный молоток                  10
Name: count, Length: 82, dtype: int64

In [84]:
labels_df = df[['номер темы', 'тема']]
labels_df = labels_df.drop_duplicates(subset=['номер темы'])
labels_df = labels_df.sort_values(by='номер темы')
labels_df

     номер темы                 тема
906           0     Отбойный молоток
39            1                  УШМ
41            2   УШМ аккумуляторная
361           3             бензобур
330           4            бензопила
..          ...                  ...
105          77   фен аккумуляторный
155          78               фрезер
163          79  шлифовальная машина
636          80   шнек для бензобура
106          81            штроборез

[82 rows x 2 columns]

In [85]:
labels_df.to_csv('../dataset/labels.csv')

In [86]:
# 2. Загружаем модель и токенизатор
import os
with open('hf_token.txt', encoding='utf-8') as f:
    token = f.read()
os.environ["HF_TOKEN"] = token
# model_name = "cointegrated/rubert-tiny2"
model_name = "DeepPavlov/rubert-base-cased"
tokenizer = AutoTokenizer.from_pretrained(model_name)
model = AutoModelForSequenceClassification.from_pretrained(model_name, num_labels=len(labels_df))

Some weights of BertForSequenceClassification were not initialized from the model checkpoint at DeepPavlov/rubert-base-cased and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

In [87]:
from sklearn.model_selection import train_test_split

train, temp = train_test_split(df, test_size=0.1, random_state=42)
val, test = train_test_split(temp, test_size=0.5, random_state=42)

print(f"Train: {len(train)}, Val: {len(val)}, Test: {len(test)}")

Train: 1346, Val: 75, Test: 75

In [88]:
train_texts = train['текст'].tolist()
train_labels = train['номер темы'].tolist()
val_texts = val['текст'].tolist()
val_labels = val['номер темы'].tolist()
test_texts = test['текст'].tolist()
test_labels = test['номер темы'].tolist()

train_dataset = IntentDataset(train_texts, train_labels, tokenizer)
val_dataset = IntentDataset(val_texts, val_labels, tokenizer)

In [89]:
# 4. Настраиваем параметры обучения
training_args = TrainingArguments(
    output_dir='./results',
    num_train_epochs=20,          
    per_device_train_batch_size=4, # маленький батч для CPU
    per_device_eval_batch_size=4,
    eval_strategy="epoch",
    save_strategy="epoch",
    dataloader_pin_memory=False,
    logging_steps=5,
    load_best_model_at_end=True,
    metric_for_best_model="accuracy",
)

In [90]:
# 5. Функция для подсчёта метрик
def compute_metrics(eval_pred):
    predictions, labels = eval_pred
    predictions = np.argmax(predictions, axis=1)
    acc = accuracy_score(labels, predictions)
    f1 = f1_score(labels, predictions, average='weighted')
    return {
        'accuracy': acc,
        'f1': f1
    }

In [91]:
# 6. Запускаем обучение
trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=train_dataset,
    eval_dataset=val_dataset,
    compute_metrics=compute_metrics,
    callbacks=[EarlyStoppingCallback(early_stopping_patience=3)]
)

print("🚀 Начинаем обучение...")
trainer.train()

🚀 Начинаем обучение...

TrainOutput(global_step=4381, training_loss=0.9131844186491259, metrics={'train_runtime': 2693.8167, 'train_samples_per_second': 9.993, 'train_steps_per_second': 2.502, 'total_flos': 1151806045977600.0, 'train_loss': 0.9131844186491259, 'epoch': 13.0})

In [92]:
# 7. Сохраняем модель
dir_name = model_name.replace('/', '_')
model.save_pretrained(os.path.join('..', 'models', dir_name))
tokenizer.save_pretrained(os.path.join('..', 'models', dir_name))

print("✅ Модель сохранена")

✅ Модель сохранена

In [94]:
device = torch.device("cpu")

# 8. Тестируем модель на новых фразах
def predict_intent(text, model, tokenizer):
    model.to(device)
    model.eval()
    inputs = tokenizer(text, return_tensors="pt", truncation=True, padding=True, max_length=128)
    
    with torch.no_grad():
        outputs = model(**inputs)
        predictions = torch.softmax(outputs.logits, dim=-1)
        # print(predictions)
        predicted_class = torch.argmax(predictions, dim=-1).item()
        confidence = predictions[0][predicted_class].item()
    
    return predicted_class, confidence

acc = 0
for test_text, test_label in zip(test_texts, test_labels):
    # print(test_text)
    pred, conf = predict_intent(test_text, model, tokenizer)

    if pred==test_label:
        symbol = '🍏'
    else:
        symbol = '🍎'
    
    print(f"{symbol} '{test_text}' -> {labels_df.loc[labels_df['номер темы'] == pred, 'тема'].values[0]} (уверенность: {conf:.2f})")
    acc += pred==test_label
    print (labels_df.loc[labels_df['номер темы'] == test_label, 'тема'])
print(f'Точность: {acc/len(test_texts)}')

🍏 '  полировальной машинки ?' -> машина полировальная (уверенность: 0.99)
12    машина полировальная
Name: тема, dtype: object
🍏 '!   распиловочный станок?' -> станок распиловочный (уверенность: 0.98)
417    станок распиловочный
Name: тема, dtype: object
🍏 '!  у вас взять болгарку (ушм) на два дня? сколько будет стоить? и  ли залог?' -> УШМ (уверенность: 0.99)
39    УШМ
Name: тема, dtype: object
🍏 '  нужна тачка для работы на стройке  ' -> тачка (уверенность: 0.99)
279    тачка
Name: тема, dtype: object
🍏 '!  на завтра забронировать строительный миксер ручной? скорее всего на сутки т.к. до 18-00 не успею вернуть.' -> миксер (уверенность: 0.99)
66    миксер
Name: тема, dtype: object
🍏 ' есть ли бензорез с 400 диском в  на одни сутки?' -> бензорез (уверенность: 0.99)
34    бензорез
Name: тема, dtype: object
🍎 '.  с большим диском по бетону на сутки по какой цене будет?' -> гвоздезабивной пистолет по бетону (уверенность: 0.72)
34    бензорез
Name: тема, dtype: object
🍏 '    краскопульта   покрасить потолок с вентиляцией 200кв  какие варианты есть?   владимир  89531790859' -> краскопульт (уверенность: 0.99)
7    краскопульт
Name: тема, dtype: object
🍏 '
привет есть ли у вас в прокате инструмент для бурения бетона алмазной коронкой?' -> дрель для алмазного бурения (уверенность: 0.87)
173    дрель для алмазного бурения
Name: тема, dtype: object
🍏 '.   есть ли в  электрический рубанок шириной 20 мм глубиной от 4 мм?' -> нет такого инструмента (уверенность: 0.54)
11    нет такого инструмента
Name: тема, dtype: object
🍏 '
   ли арендовать бензорез на выходные?' -> бензорез (уверенность: 0.99)
34    бензорез
Name: тема, dtype: object
🍏 '' -> не вопрос клиента (уверенность: 1.00)
4    не вопрос клиента
Name: тема, dtype: object
🍏 '! у вас воз на завтра с доставкой заказать бенз.трамбовку на 90 кг. адрес доставки: улица понссе территория южная часть производственной зоны горелово виллозское г.п. ломоносовский район. работаеи по безналу с ндс.' -> виброплита (уверенность: 0.99)
146    виброплита
Name: тема, dtype: object
🍏 '' -> не вопрос клиента (уверенность: 1.00)
4    не вопрос клиента
Name: тема, dtype: object
🍏 ' а лобзик есть?' -> лобзик (уверенность: 1.00)
32    лобзик
Name: тема, dtype: object
🍏 '. что кроме оплаты аренды  чтобы оформить  строительного пылесоса?' -> пылесос (уверенность: 1.00)
1    пылесос
Name: тема, dtype: object
🍏 '
   фена для труб –  стык прогреть перед пайкой' -> фен (уверенность: 0.99)
3    фен
Name: тема, dtype: object
🍏 '
 ли у вас арендовать бензобур для фундамента на пару дней' -> бензобур (уверенность: 0.98)
361    бензобур
Name: тема, dtype: object
🍏 '   циклевочной машины. хотела бы узнать условия и есть ли  на завтра.' -> паркетно-шлифовальная машина (уверенность: 1.00)
5    паркетно-шлифовальная машина
Name: тема, dtype: object
🍏 ' реноватор есть в  на сегодня  ?' -> реноватор (уверенность: 0.99)
260    реноватор
Name: тема, dtype: object
🍏 '    краскопульта на 08.05   условия' -> краскопульт (уверенность: 0.99)
7    краскопульт
Name: тема, dtype: object
🍏 '    дизельной тепловой пушки на выходные' -> пушка дизельная (уверенность: 0.98)
789    пушка дизельная
Name: тема, dtype: object
🍏 '
привет ищу ленточную пилу для резки металла у вас такое есть?' -> пила ленточная (уверенность: 0.99)
287    пила ленточная
Name: тема, dtype: object
🍏 '
   ли взять ленточную пилу на выходные?' -> пила ленточная (уверенность: 0.99)
287    пила ленточная
Name: тема, dtype: object
🍎 '!  нейлер telegram номер 911 948-78-14' -> степлер (уверенность: 0.99)
11    нет такого инструмента
Name: тема, dtype: object
🍏 'доброй ночи в какую стоимость  циклевальной машины для паркета дубового ?' -> паркетно-шлифовальная машина (уверенность: 1.00)
5    паркетно-шлифовальная машина
Name: тема, dtype: object
🍏 '  какая цена аренды генератора ?    под мойку высокого давления' -> генератор (уверенность: 0.93)
23    генератор
Name: тема, dtype: object
🍏 ' сколько будет стоить перфоратор на 1-2 часа' -> перфоратор (уверенность: 1.00)
6    перфоратор
Name: тема, dtype: object
🍏 ' торцевую пилу в какую стоимость  взять в  на день?' -> торцовочная пила (уверенность: 1.00)
31    торцовочная пила
Name: тема, dtype: object
🍏 '' -> не вопрос клиента (уверенность: 1.00)
4    не вопрос клиента
Name: тема, dtype: object
🍏 '!  сколько будет стоить лобзик в ' -> лобзик (уверенность: 1.00)
32    лобзик
Name: тема, dtype: object
🍏 ' есть перфоратор или ударная дрель ?' -> перфоратор (уверенность: 1.00)
6    перфоратор
Name: тема, dtype: object
🍏 '
  взять лампу для исследований что у вас есть?' -> лампа Лосева (уверенность: 0.99)
218    лампа Лосева
Name: тема, dtype: object
🍎 '.   дисковой циклевочной машины. на следующей неделе вт-ср-чт' -> пила дисковая (уверенность: 0.93)
5    паркетно-шлифовальная машина
Name: тема, dtype: object
🍏 ' скажите маленькую болгарку  в  у вас взять? и по какой цене?' -> УШМ (уверенность: 1.00)
39    УШМ
Name: тема, dtype: object
🍏 '! есть в аренде бур 28х1000 и 32х1000 под sds plus. сколько на сутки один и второй бур и если оба сразу возьму в  цена такая же? мне на полдня максимум день. спасибо' -> бур для перфоратора (уверенность: 0.99)
40    бур для перфоратора
Name: тема, dtype: object
🍏 'сообщение удалено' -> не вопрос клиента (уверенность: 1.00)
4    не вопрос клиента
Name: тема, dtype: object
🍏 ' нужна тачка для перевозки земли на даче   на день' -> тачка (уверенность: 0.99)
279    тачка
Name: тема, dtype: object
🍏 '  строительный пылесос и шлифовальная машина по бетону для потолка есть ли а вас ? что для этого ?' -> пылесос (уверенность: 1.00)
1    пылесос
Name: тема, dtype: object
🍏 '
привет сколько будет стоить  заклепочника на выходные?' -> заклепочник (уверенность: 0.99)
286    заклепочник
Name: тема, dtype: object
🍎 '
привет ищу технику для чистки ковров в квартиру что посоветуете?' -> металлоискатель (уверенность: 0.48)
74    моющий пылесос
Name: тема, dtype: object
🍏 '!  взять дрель  шуруповерт в  завтра на день . сколько это будет стоить ?' -> дрель-шуруповерт (уверенность: 1.00)
0    дрель-шуруповерт
Name: тема, dtype: object
🍏 '
 взять в  бур для перфоратора на выходные?  сделать отверстия под анкера' -> бур для перфоратора (уверенность: 0.99)
40    бур для перфоратора
Name: тема, dtype: object
🍏 '
привет ищу оборудование для продольного распила бруса что у вас есть ' -> станок распиловочный (уверенность: 0.54)
417    станок распиловочный
Name: тема, dtype: object
🍏 '!    генератор для работы на складе большом для клининговых услуг и уборке после строительства. ваш генератор подойдет под эти цели? какая стоимость выйдет на 3 дня? какие условия? спасибо!' -> генератор (уверенность: 1.00)
23    генератор
Name: тема, dtype: object
🍏 ' сколько будет стоить  строительного пылесоса с мешком для мусора?' -> пылесос (уверенность: 1.00)
1    пылесос
Name: тема, dtype: object
🍎 '! сколько будет стоить  электропилы на 2 дня ? и куда  подъехать? часы работы' -> пушка электрическая (уверенность: 0.47)
11    нет такого инструмента
Name: тема, dtype: object
🍏 '  планирую делать отверстия в фундаменте нужна установка для алмазного бурения какие условия?' -> установка алмазного бурения (уверенность: 0.54)
821    установка алмазного бурения
Name: тема, dtype: object
🍏 ' шлифовальная машина для дерева на акомулятлое есть?' -> шлифовальная машина (уверенность: 0.91)
163    шлифовальная машина
Name: тема, dtype: object
🍎 ' привет  инструмент для крепления деревянных панелей есть что-то подходящее?' -> степлер (уверенность: 0.99)
126    нейлер пневматический
Name: тема, dtype: object
🍏 ' меня  2)лазерный уровень если да то сколько будет стоить  на 2 суток' -> лазерный уровень (уверенность: 0.99)
140    лазерный уровень
Name: тема, dtype: object
🍏 '. скажите   строительного пылесоса(уборка квартиры после установки дверей подвесных потолков). с доставкой инструмента. район адмиралтейский. ул. набережная обводного канала.' -> пылесос (уверенность: 1.00)
1    пылесос
Name: тема, dtype: object
🍏 '. вы сегодня работаете? если да то у вас есть стремянка на 7 ступеней (1.48м площадка) в ? и сколько это по стоимости на сутки' -> лестница (уверенность: 1.00)
8    лестница
Name: тема, dtype: object
🍏 '
привет ищу прибор для разметки потолка под гипсокартон что посоветуете' -> лазерный уровень (уверенность: 0.99)
140    лазерный уровень
Name: тема, dtype: object
🍏 '!  ли на завтра арендовать перфоратор? и  на какое количество часов  арендовать?' -> перфоратор (уверенность: 1.00)
6    перфоратор
Name: тема, dtype: object
🍏 '.   краскопульта?' -> краскопульт (уверенность: 0.99)
7    краскопульт
Name: тема, dtype: object
🍏 '. у вас есть резьбонарезной ручной станок?' -> нет такого инструмента (уверенность: 0.99)
11    нет такого инструмента
Name: тема, dtype: object
🍏 '. а нет ли такой возсти чтобы и мастера вместе с инструментом пригласить?  болгаркой отпилить  полосу на декоративной плитке на балконе ?' -> УШМ (уверенность: 0.99)
39    УШМ
Name: тема, dtype: object
🍏 '
  бур под перфоратор для плитки что посоветуете?' -> бур для перфоратора (уверенность: 0.99)
40    бур для перфоратора
Name: тема, dtype: object
🍏 '   полуавтомата' -> сварочный полуавтомат (уверенность: 1.00)
25    сварочный полуавтомат
Name: тема, dtype: object
🍎 '
привет есть ли у вас в прокате газовая тепловая пушка для стройки?' -> пушка газовая (уверенность: 0.99)
436    пушка тепловая
Name: тема, dtype: object
🍏 '   дрели?' -> дрель-шуруповерт (уверенность: 1.00)
0    дрель-шуруповерт
Name: тема, dtype: object
🍏 ' коллеги' -> не вопрос клиента (уверенность: 1.00)
4    не вопрос клиента
Name: тема, dtype: object
🍎 '  нужна установка для алмазного бурения на пару часов сколько будет стоить?' -> дрель для алмазного бурения (уверенность: 0.57)
821    установка алмазного бурения
Name: тема, dtype: object
🍏 '
привет  взять бензорез на пару часов чтобы порезать трубы какие условия?' -> бензорез (уверенность: 0.99)
34    бензорез
Name: тема, dtype: object
🍏 ' у вас есть аккумуляторная болгарка?' -> УШМ аккумуляторная (уверенность: 0.99)
41    УШМ аккумуляторная
Name: тема, dtype: object
🍏 '
  мощный молот для демонтажа бетонной стены есть такие в прокате?' -> отбойный молоток (уверенность: 0.98)
119    отбойный молоток
Name: тема, dtype: object
🍏 '! сколько у вас стоит арендовать фрезер ручной?' -> фрезер (уверенность: 0.99)
155    фрезер
Name: тема, dtype: object
🍏 ' есть ли у вас  следующие инструменты?  болгарка с диском по металлу   взять в  завтра в середине дня на двое суток. и сориентируйте  по стоимости.' -> УШМ (уверенность: 0.96)
39    УШМ
Name: тема, dtype: object
🍏 '  перфоратор в . 2 отверстия сделать' -> перфоратор (уверенность: 1.00)
6    перфоратор
Name: тема, dtype: object
🍎 ' привет есть ли у вас аккумуляторная пила сабельная ? нужна на день' -> сабельная пила (уверенность: 0.93)
97    сабельная пила аккумуляторная
Name: тема, dtype: object
🍏 '
  стоимость аренды компрессора на неделю для строительных работ' -> компрессор (уверенность: 0.99)
13    компрессор
Name: тема, dtype: object
🍏 '
 есть ли у вас в прокате ямобур для земляных работ' -> бензобур (уверенность: 0.98)
361    бензобур
Name: тема, dtype: object
🍎 ' есть кондуктор для установке межкомнатных дверей' -> металлоискатель (уверенность: 0.37)
11    нет такого инструмента
Name: тема, dtype: object
🍏 '! у вас есть шуруповерт в ?' -> дрель-шуруповерт (уверенность: 1.00)
0    дрель-шуруповерт
Name: тема, dtype: object
Точность: 0.8666666666666667